[profile.default]
solc = "0.8.24"
evm_version="cancun"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 300
verbosity = 2
src = "src"
test = "test"
out = "out"
libs = ["lib"]
extra_output_files = [
  "abi",
  "evm.bytecode"
]
fs_permissions = [{ access = "read", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config